<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-31T07:05:16 IST" name="Suite" finished-at="2022-08-31T07:05:34 IST" duration-ms="17788">
    <groups>
    </groups>
    <test started-at="2022-08-31T07:05:16 IST" name="Test" finished-at="2022-08-31T07:05:34 IST" duration-ms="17788">
      <class name="TestCases.VerifyLoginTestCases">
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:TestCases.VerifyLoginTestCases@479d31f3]" started-at="2022-08-31T07:05:16 IST" name="LaunchBrowser" finished-at="2022-08-31T07:05:21 IST" duration-ms="5404" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="login()[pri:0, instance:TestCases.VerifyLoginTestCases@479d31f3]" started-at="2022-08-31T07:05:21 IST" name="login" finished-at="2022-08-31T07:05:23 IST" duration-ms="1672" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCases.VerifyLoginTestCases@479d31f3]" started-at="2022-08-31T07:05:23 IST" name="TearDown" finished-at="2022-08-31T07:05:23 IST" duration-ms="265" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestCases.VerifyLoginTestCases -->
      <class name="TestCases.VerifySignUpTestCases">
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:TestCases.VerifySignUpTestCases@6b927fb]" started-at="2022-08-31T07:05:23 IST" name="LaunchBrowser" finished-at="2022-08-31T07:05:28 IST" duration-ms="4190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="SignUp()[pri:0, instance:TestCases.VerifySignUpTestCases@6b927fb]" started-at="2022-08-31T07:05:28 IST" name="SignUp" finished-at="2022-08-31T07:05:33 IST" duration-ms="5872" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Fre CRM Trial: Salesforce 30-Day Trial - Salesforce IN] but found [Free CRM Trial: Salesforce 30-Day Trial - Salesforce IN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Fre CRM Trial: Salesforce 30-Day Trial - Salesforce IN] but found [Free CRM Trial: Salesforce 30-Day Trial - Salesforce IN]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.CommonUtilities.AssertionHandling(CommonUtilities.java:20)
at TestCases.VerifySignUpTestCases.SignUp(VerifySignUpTestCases.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignUp -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestCases.VerifySignUpTestCases@6b927fb]" started-at="2022-08-31T07:05:33 IST" name="TearDown" finished-at="2022-08-31T07:05:34 IST" duration-ms="324" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestCases.VerifySignUpTestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
